### ISSUE TITLE
The token expired, was revoked, or the token ID is incorrect. Please log back in to re-authenticate.

### ISSUE THREAD

**Issue by megalucio** [spring-cloud-services-samples/cook#11]
Following instructions after executing step 2 

> ./scripts/deploy.sh target/cook-0.0.1-SNAPSHOT.jar

I get following message:

Creating Config Server...The token expired, was revoked, or the token ID is incorrect. Please log back in to re-authenticate.

**Comment by royclarkson** [comment]
The script attempts to deploy the sample app and create services in the Pivotal Cloud Foundry org and space where you are currently targeted. Please confirm that you are authenticated and targeting the desired space. Thanks.

**Comment by csterwa** [comment]
Closing.

**Comment by scr4318** [comment]
Getting the same error, after successful cf login via Jenkins script file.
However when same commands are run from cmd prmpt, works perfectly fine.

**Comment by jade290** [comment]
I'm using React. I'm getting this message because in my manifest.yml file has a field "GRANT_TYPE" under the "env" variable declaration where my token has expired. It needs to be updated by going off to a website and renewing it. Problem is that initially the terminal gave me that website URL and now it doesn't.
